-- =========================================================
-- Script de base de datos - Equinorte Invoice
-- Motor: PostgreSQL 15+
-- Objetivo: crear tablas y cargar datos de prueba para validar
-- el recalculo proporcional de facturas.
-- =========================================================

DROP TABLE IF EXISTS invoice_details;
DROP TABLE IF EXISTS invoice;

CREATE TABLE invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subtotal NUMERIC(38, 2) NOT NULL,
    total_iva NUMERIC(38, 2) NOT NULL,
    total NUMERIC(38, 2) NOT NULL
);

CREATE TABLE invoice_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    iva NUMERIC(38, 2) NOT NULL,
    total NUMERIC(38, 2) NOT NULL,
    invoice_id BIGINT NOT NULL,
    CONSTRAINT fk_invoice_details_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES invoice (id)
        ON DELETE CASCADE
);

-- =========================================================
-- Facturas de prueba
-- =========================================================

INSERT INTO invoice (id, subtotal, total_iva, total)
VALUES
    (1, 150000.00, 28500.00, 178500.00),
    (2, 220000.00, 41800.00, 261800.00);

-- =========================================================
-- Detalles factura 1
-- Subtotal: 150000
-- IVA 19%: 28500
-- Total: 178500
-- =========================================================

INSERT INTO invoice_details (product_name, price, iva, total, invoice_id)
VALUES
    ('Excavadora Caterpillar 320D (Alquiler diario)', 80000.00, 15200.00, 95200.00, 1),
    ('Mezcladora de concreto industrial (Alquiler diario)', 40000.00, 7600.00, 47600.00, 1),
    ('Andamios metalicos (Paquete semanal)', 30000.00, 5700.00, 35700.00, 1);

-- =========================================================
-- Detalles factura 2
-- Subtotal: 220000
-- IVA 19%: 41800
-- Total: 261800
-- =========================================================

INSERT INTO invoice_details (product_name, price, iva, total, invoice_id)
VALUES
    ('Compactadora de suelo (Alquiler diario)', 70000.00, 13300.00, 83300.00, 2),
    ('Generador electrico 15kVA (Alquiler diario)', 90000.00, 17100.00, 107100.00, 2),
    ('Vibrador de concreto (Alquiler diario)', 60000.00, 11400.00, 71400.00, 2);

-- Reinicia las secuencias identity para que nuevas inserciones sigan
-- despues de los IDs cargados manualmente.
SELECT setval(pg_get_serial_sequence('invoice', 'id'), COALESCE(MAX(id), 1), true)
FROM invoice;

SELECT setval(pg_get_serial_sequence('invoice_details', 'id'), COALESCE(MAX(id), 1), true)
FROM invoice_details;

-- =========================================================
-- Consultas rapidas de verificacion
-- =========================================================

SELECT
    i.id,
    i.subtotal,
    i.total_iva,
    i.total,
    COUNT(d.id) AS productos
FROM invoice i
LEFT JOIN invoice_details d ON d.invoice_id = i.id
GROUP BY i.id, i.subtotal, i.total_iva, i.total
ORDER BY i.id;
