spring:
  application:
    name: invoice

  datasource:
    url: jdbc:postgresql://localhost:5432/invoice_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true   # 🔥 AQUÍ VA
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always